# frozen_string_literal: true

require 'rpl/words/branch'
require 'rpl/words/display'
require 'rpl/words/general'
require 'rpl/words/mode'
require 'rpl/words/operations'
require 'rpl/words/program'
require 'rpl/words/stack'
require 'rpl/words/store'
require 'rpl/words/string-list'
require 'rpl/words/test'
require 'rpl/words/time-date'
require 'rpl/words/trig'
require 'rpl/words/logarithm'
require 'rpl/words/filesystem'
