# frozen_string_literal: true

require 'rpl/words/branch'
require 'rpl/words/display'
require 'rpl/words/general'
require 'rpl/words/mode'
require 'rpl/words/operations-reals'
require 'rpl/words/operations-complexes'
require 'rpl/words/operations-reals-complexes'
require 'rpl/words/program'
require 'rpl/words/repl'
require 'rpl/words/stack'
require 'rpl/words/store'
require 'rpl/words/string'
require 'rpl/words/string-list'
require 'rpl/words/test'
require 'rpl/words/time-date'
require 'rpl/words/trig'
require 'rpl/words/logarithm'
require 'rpl/words/filesystem'
require 'rpl/words/system'
require 'rpl/words/list'
